### ISSUE TITLE
UTFT

### ISSUE THREAD

**Issue by rebboc** [greiman/ChibiOS-Arduino#3]
I am designing LED lighting for an outdoor area behind our house.  I plan to use an Arduino Due with a small LCD touch screen as the controller.  I am going to use the UTFT and UTouch libraries by Henning Karlsen to control the display.  As I want to simplify future expansion of the system, (and also to learn about RTOS's)  I am thinking of using ChibiOS on the Due.  Do you know if UTFT and UTouch are compatible with ChibiOS?

**Comment by greiman** [comment]
I have no idea.

**Comment by ladislas** [comment]
@rebboc the best way is to test with a simple example ;)
