### ISSUE TITLE
`chThdExit' referenced error when compileing AVR w/1.6.9 and 1.6.10 IDE

### ISSUE THREAD

**Issue by kd8bxp** [greiman/ChibiOS-Arduino#4]
I get the following error when I try to compile any of the AVR example sketches using the Arduino IDE 1.6.9 or 1.6.10 - 64-bit linux versions.  I have not tried this with a Windows machine.
The ARM examples appear to compile correctly - thou I don't have a ARM board to try them on.

`chThdExit' referenced in section `.text' of /tmp/ccnXxBcW.ltrans0.ltrans.o: defined in discarded section `.text' of libraries/ChibiOS_AVR/utility/chthreads.c.o (symbol from plugin)
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino/Genuino Uno.

I'm not sure what this error is trying to tell me or how to proceed.

**Comment by greiman** [comment]
Can't help.  The examples I tried runs on Windows 10 with IDE 1.6.11.

**Comment by kd8bxp** [comment]
hmmm, interesting.
Updated my IDE to 1.6.12, downgraded the AVR boards to 1.6.10 and now it compiles.
Was unaware of these problems till now, so you did help. Thanks.
