### ISSUE TITLE
Cant compile on STM32F103C

### ISSUE THREAD

**Issue by shaddow501** [greiman/ChibiOS-Arduino#9]
Dear Sir,

Before I start to modify the code I start by testing the simple example code to see if it works and proceed from there.. 
When I try to compile the basic code "chBlink" on Arduino IDE V16.11 and latest 1.8.1 I get this error.

ChibiOS_ARM\src/utility/chcore_v7m.h:380:48: error: 'NVIC_SetPriorityGrouping' was not declared in this scope
ChibiOS_ARM\src/utility/chcore_v7m.h:389:20: error: 'SVCall_IRQn' was not declared in this scope

ChibiOS_ARM\src/utility/chcore_v7m.h:389:55: error: 'NVIC_SetPriority' was not declared in this scope

well other many all related to the chcore_v7m.h.

I didnt do anything just test the code and I wonder why it doesnt compile.

**Comment by greiman** [comment]
This is line two of the readme.txt file:
AVR, Due, and Teensy 3.x boards are supported.
